---
lint:
  stage: lint
  image: "${GO_IMAGE}"
  script:
    - chmod +x ./.gitlab/ci/scripts/lint.sh
    - ./.gitlab/ci/scripts/lint.sh
  rules:
    - changes:
        - 'internal/*'
        - 'pkg/*'
        - '/*.go'
  allow_failure: true
