---
.install-chart:
  stage: deploy
  image:
    name: "${HELM_IMAGE}"
    entrypoint: [""]
  script:
    - chmod +x ./.gitlab/ci/scripts/chart-install.sh
    - ./.gitlab/ci/scripts/chart-install.sh
  when: manual

chart:production:install:
  extends: .install-chart
  only:
    - tags
  variables:
    KUBE_TOKEN: "${KUBE_PRODUCTION_TOKEN}"
  needs:
    - image:production:push
