---
.release:
  stage: release
  image: "${OC_IMAGE}"
  script:
    - chmod +x ./.gitlab/ci/scripts/release.sh
    - ./.gitlab/ci/scripts/release.sh

release:production:push:
  extends: .release
  needs:
    - config:production:push
  variables:
    KUBE_APISERVER: ""
    KUBE_NAMESPACE: ""
    KUBE_TOKEN: "${KUBE_PRODUCTION_TOKEN}"
