apiVersion: v1
kind: Application
metadata:
  name: node-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amirhnajafiz/node-app
    targetRevision: HEAD
  destination:
    server: https://node-app.default.apps.ir-teh2.arvancloud.ir
    namespace: argocd
stringData:
  name: node-app
  url: https://github.com/amirhnajafiz/node-app/deployments/node-app
  type: helm
