compile:
  stage: compile
  extends:
    - .golang-cache
  image: "${GO_IMAGE}"
  script:
    - chmod +x ./.gitlab/ci/scripts/compile.sh
    - ./.gitlab/ci/scripts/compile.sh
  artifacts:
    name: "${DEPLOYMENT_NAME}-${CI_COMMIT_REF_SLUG}"
    paths:
      - ./app
    expire_in: 1 week
  cache:
    policy: pull-push
