---
build:
  image: docker:latest
  stage: build
  script:
    - chmod +x ./.gitlab/ci/scripts/build.sh
    - ./.gitlab/ci/scripts/build.sh
  artifacts:
    paths:
      - ${CI_PROJECT_NAME}-${CI_COMMIT_REF_SLUG}.tar
    expire_in: 1 week
